name: Report Scheduled Issue
description: Reports failure or warning of a scheduled workflow run to Slack

inputs:
  slack-webhook:
    description: Slack incoming webhook URL
    required: true
  event:
    description: Description of what happened, used in the message (e.g. "failed", "has warnings")
    required: true

runs:
  using: composite
  steps:
    - name: Report issue from a scheduled run
      uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
      with:
        webhook: ${{ inputs.slack-webhook }}
        webhook-type: incoming-webhook
        # Try Slack's "Block Kit Builder" to experiment with message formatting:
        # https://app.slack.com/block-kit-builder/
        # The top-level "text" field is used in contexts where blocks are not supported, like mobile notifications.
        payload: |
          text: "${{ github.workflow }} ${{ inputs.event }} for ${{ github.repository }}."
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: "${{ github.workflow }} ${{ inputs.event }} for ${{ github.repository }}."
            - type: "section"
              text:
                type: "mrkdwn"
                text: "Please check the <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for details."
